<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Entities\Catalog\" />
    <Folder Include="Entities\Community\" />
    <Folder Include="Entities\Observation\" />
  </ItemGroup>

</Project>
